server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

cors:
  proxy-url: ${CORS_NGROK_URL:https://ffffff.eu.ngrok.io}

spring:
  profiles:
    active: presentation
  datasource:
    url: jdbc:postgresql://localhost:5432/atm-dev
    username: atm
    password: 666666
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto:
        create
    show-sql: true
  quartz:
    wait-for-jobs-to-complete-on-shutdown: false
    job-store-type: jdbc
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.skipUpdateCheck: true
      org.quartz.threadPool.threadCount: 2
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  batch:
    jdbc:
      initialize-schema: always
  web:
    resources:
      static-locations: /

---

spring:
  datasource:
    hikari:
      connection-timeout: 4000
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto:
        create
    show-sql: true
  config:
    activate:
      on-profile: test, presentation
  h2:
    console:
      enabled: true
  quartz:
    properties:
      org.quartz.jobStore.isClustered: false


---

